### ISSUE TITLE
Server Feezing after some time.

### ISSUE THREAD

**Issue by comonier** [TheBusyBiscuit/ExoticGarden#70] opened 2019-06-22 16:30 UTC
## Description (Required)
Server Feezes after some time.

## Steps to reproduce the Issue (Required)
five minuts of server and it freezes

## Expected behavior (Required)
wait

## Server Log / Error Report
Freezing Log.
https://paste.ofcode.org/jNBKsV7HzakFWBpih5E2Lq
Full Log: https://paste.ofcode.org/9zacX2K79GFhdkp2nGpq2t

## Environment (Required)
CS-CoreLib-60.jar
ExoticGarden-11.jar
Slimefun4-121.jar
git-Spigot-df0eb25-da071ec (MC: 1.14.2)

**Comment by TheBusyBiscuit** [comment] 2019-06-22 16:32
Still a duplicate of #63 -_-

**Closed by TheBusyBiscuit** 2019-06-22 16:32 UTC
Labels: Bug Report
