### ISSUE TITLE
trees

### ISSUE THREAD

**Issue by threlief** [TheBusyBiscuit/ExoticGarden#105] opened 2020-01-25 20:37 UTC
#Description (Required)
so for some reason the slimefun exotic garden trees do not work anymore they only planting ans regular trees even though the sappling says otherwise we had vers408 and updated to 410 neither versions is fixing the problem

Steps to reproduce the Issue (Required)
we tried updating the versions and still nothing

Expected behavior (Required)
I expeted to have the fruits grow for the cherry and other treesi

Server Log / Error
25.01 15:23:00 [Server] ERROR Could not pass event StructureGrowEvent to ExoticGarden vDEV - 25 (git b5fce971)
25.01 15:23:00 [Server] INFO java.lang.NullPointerException: null
25.01 15:23:00 [Server] INFO at me.mrCookieSlime.ExoticGarden.Schematic.Schematic.pasteSchematic(Schematic.java:111) ~[?:?]
25.01 15:23:00 [Server] INFO at me.mrCookieSlime.ExoticGarden.PlantsListener.onGrow(PlantsListener.java:61) ~[?:?]
25.01 15:23:00 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor609.execute(Unknown Source) ~[?:?]

Environment (Required)
Minecraft Version:1.15.1
Slimefun Version: 410
CS-CoreLib Version: 80
ExoticGarden version: 25

**Comment by TheBusyBiscuit** [comment] 2020-01-25 20:38
Duplicate of #104

**Closed by TheBusyBiscuit** 2020-01-25 20:38 UTC
Labels: Bug Report

**Comment by threlief** [comment] 2020-01-25 20:39
IT IS NOT A DUPLICATE GRRRR

**Comment by threlief** [comment] 2020-01-25 20:40
i didnt use world edit or fill

**Comment by threlief** [comment] 2020-01-25 20:40
HELLO

**Comment by TheBusyBiscuit** [comment] 2020-01-25 20:40
It is. It's the same error.
Just be patient and stop spamming...

**Comment by threlief** [comment] 2020-01-25 20:45
sorry for spamming i just keep getting my ticket closed with no reason and the subject of the other was different this is my first time doing this so sorry

**Comment by TheBusyBiscuit** [comment] 2020-01-25 20:46
It wasn't for no reason...
The reason was always posted there.
You should maybe just start to read why it was closed instead of being so choleric...
