### ISSUE TITLE
Heads on trees don't have the fruit textures

### ISSUE THREAD

**Issue by GrGadam** [TheBusyBiscuit/ExoticGarden#130] opened 2020-04-28 07:59 UTC
## Description (Required)
On slimefun trees, only steve heads appear, and when you break it, they turn back to fruits. Bushes don't have this problem

## Steps to reproduce the Issue (Required)
Install Exoticgarden DEV 41 and most of the trees it generates will be like that.

## Expected behavior (Required)
Show the skins of the heads on the trees, not the basic steve and alex heads.

## Server Log / Error Report
It doesn't show any errors in the server log.

## Environment (Required)
Only CS-Corelib, Slimefun, Exoticgarden are installed.

 - Minecraft Version: Paper 1.15.2 #226
 - CS-CoreLib Version: DEV 85
 - Slimefun Version: DEV 494
 - ExoticGarden Version: DEV 41

**Comment by TheBusyBiscuit** [comment] 2020-04-28 08:21
Duplicate of #129

**Closed by TheBusyBiscuit** 2020-04-28 08:21 UTC
Labels: Bug Report
