### ISSUE TITLE
Server randomly crashes after playing on it whilst ExoticGarden is installed.

### ISSUE THREAD

**Issue by EnderBro123** [TheBusyBiscuit/ExoticGarden#72] opened 2019-06-23 17:09 UTC
## Description (Required)

Server randomly crashes after playing on it whilst ExoticGarden is installed.

## Steps to reproduce the Issue (Required)

Install ExoticGarden. Play on the server until it freezes and times you out.

## Expected behavior (Required)

Not to crash.

## Server Log / Error Report

Only error I get is Paper warning me about the server lagging. Here's the Pastebin anyway. https://pastebin.com/Grze9432

## Environment (Required)

![2019-06-23_10 08 36](https://user-images.githubusercontent.com/51277766/59979607-e7edbf00-959e-11e9-92bb-efaf0a08bbee.png)

**Comment by TheBusyBiscuit** [comment] 2019-06-23 17:11
Duplicate of #63

**Closed by TheBusyBiscuit** 2019-06-23 17:11 UTC
Labels: Bug Report
