### ISSUE TITLE
exotic trees

### ISSUE THREAD

**Issue by threlief** [TheBusyBiscuit/ExoticGarden#117] opened 2020-02-18 08:30 UTC
## Description (Required)
we can not find them in the wild or plant them 

## Steps to reproduce the Issue (Required)
we tried restarting server even tried changing the files and still wont work

## Expected behavior (Required)
they normally grow in wild at least but wont even do that now

## Server Log / Error Report
BOT Server Chat: [Tue, 18. Feb 2020 03:20:30 EST WARN] Could not paste Schematic for Tree: OAK_APPLE_TREE (ZipException)
[2:20 AM]  BOT Server Chat: [Tue, 18. Feb 2020 03:20:31 EST WARN] Could not paste Schematic for Tree: ORANGE_TREE (ZipException)

does it for all the trees

## Environment (Required)

we have tried multiple versions of each

 - Minecraft Version:1.15.1
 - CS-CoreLib Version: 83 & 89 we have tried cpl others
 - Slimefun Version: 444 & 4-6
 - ExoticGarden Version: 31, 33, 35

**Comment by threlief** [comment] 2020-02-18 08:31
sry that i didnt fill that last one out correctly  tried editing it but u closed it too fast

**Comment by threlief** [comment] 2020-02-21 07:31
sorry been three days so wondering if u got any clue on it yet

**Comment by TheBusyBiscuit** [comment] 2020-03-01 16:15
Duplicate of #111 
Delete your /plugins/ExoticGarden/schematics folder and restart the server on the latest build.

**Closed by TheBusyBiscuit** 2020-03-01 16:15 UTC
Labels: Bug Report
