### ISSUE TITLE
Schematic can not be paste

### ISSUE THREAD

**Issue by ishi-sama** [TheBusyBiscuit/ExoticGarden#106] opened 2020-01-26 14:01 UTC
## Description (Required)
Some of Schematics can't be placed by the plugin like custom tree. 

## Steps to reproduce the Issue (Required)
Start a new server, walk arround the map, none of custom tree spawn.

## Expected behavior (Required)
All structures spawn correctly.

## Server Log / Error Report
https://pastebin.com/tQgFaaif

## Environment (Required)
https://ibb.co/2NyBvDB
https://ibb.co/vBr5DNc

 - Minecraft Version: 1.15.2
 - CS-CoreLib Version: CS-CoreLib - DEV 82 (git 96270)
 - Slimefun Version: Slimefun4 - DEV 412 (git 9f07d)
 - ExoticGarden Version: ExoticGarden - DEV 25 (git b5fce)

**Comment by TheBusyBiscuit** [comment] 2020-01-26 14:03
Duplicate of #104

**Closed by TheBusyBiscuit** 2020-01-26 14:03 UTC
Labels: Bug Report
