### ISSUE TITLE
Advanced Farmer Android disappears upon farming Dust Plants

### ISSUE THREAD

**Issue by ItsSynchro** [TheBusyBiscuit/ExoticGarden#165] opened 2020-11-12 19:04 UTC
## :round_pushpin: Description (REQUIRED)

The Advanced Farmer Android disappears after a while when farming SF dust plants
(disappears after different durations)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place the android, the fuel interface and item interface down. Let the bot SF dust/ore plants farm.
2. Load the program for the android
Program: Farming 6 blocks forward, 2 to the left, 6 to the left again, put items into Item interface, goes 1 left, turns right to get fuel. Process starts over again.
3. Wait till it despawn ( between 5-15min ) sometimes its faster sometimes it takes longer.

## :bulb: Expected behavior (REQUIRED)

The android should keep on repeating the same program over and over again till it either runs out of fuel or has no storage anymore.

## :open_file_folder: /error-reports/ Folder

https://pastebin.com/fyfNNsBg

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft Version: Tuinity 1.16.4
 - Slimefun Version: vDEV - 742
 - CS-CoreLib Version: vDEV - 91

**Comment by TheBusyBiscuit** [comment] 2020-11-14 15:13
Duplicate of #163 

You are using an outdated version of ExoticGarden that's why this happens, the bug has already been fixed a month ago.
Also, please include your ExoticGarden version when reporting an issue on this bug tracker.

**Closed by TheBusyBiscuit** 2020-11-14 15:13 UTC
Labels: Bug Report
