### ISSUE TITLE
Fruits growing with Steve heads

### ISSUE THREAD

**Issue by ChitterChatter** [TheBusyBiscuit/ExoticGarden#129] opened 2020-04-28 07:53 UTC
## Description (Required)
Hi there. My sf exotic plants and trees are growing Steve heads. When the fruit is broken, the proper skin will show up when it drops, but in the meantime it all grows as Steve heads.

## Steps to reproduce the Issue (Required)
The plants and trees just grow with the creepy Steve heads on them.
This is supposed to be an apple tree....

![image](https://user-images.githubusercontent.com/28234726/80460966-6d41ae80-88e9-11ea-9db2-7c3550be1375.png)

When you hit the fruit it drops looking how it should....

![image](https://user-images.githubusercontent.com/28234726/80461071-95311200-88e9-11ea-9949-646b7d406393.png)

## Expected behavior (Required)

The trees and bushes should have their regular fruit textures.

## Server Log / Error Report

It seems when Slimefun loaded, it loaded "duplicate" heads....

https://pastebin.com/nBsKXJDR

## Environment (Required)

 - Minecraft Version:  1.15.2 paper
 - CS-CoreLib Version:  DEV 85 (git 4a7fc)
 - Slimefun Version:  DEV 494 (git 2b9d1)
 - ExoticGarden Version: ExoticGarden - DEV 41 (git 0dd6b)

![image](https://user-images.githubusercontent.com/28234726/80460752-1b992400-88e9-11ea-9d6a-10b13721ab4f.png)

**Comment by RydelSleak** [comment] 2020-04-30 01:57
Also having this issue with all the same parameters.

 This and #130 were both closed, but I don't see a solution or anything. I'm new to Github though, so am I overlooking something here?

**Comment by Volgeop** [comment] 2020-05-01 13:30
I also have experience with this.

**Comment by TheBusyBiscuit** [comment] 2020-05-01 13:48
> Also having this issue with all the same parameters.
> 
> This and #130 were both closed, but I don't see a solution or anything. I'm new to Github though, so am I overlooking something here?
> 
> **Edit**
> 
> Sorry, just realized it meant #130 is closed, and not this one. So if this is still open then I'm assuming it's still being fixed. Learning has occurred! :D

You should probably read WHY the issue was closed.
I marked it as a duplicate since this issue right here already existed, no need to have more than one issue for the exact same thing.

**Comment by RydelSleak** [comment] 2020-05-01 14:10
No, I understood that part, that #130 was a duplicate of this post. What I didn't understand (being a new user on Github) was why it was also saying closed here.

 I thought when it said in the timeline, just above my first comment, that the issue was closed it meant #129 was closed. But now I understand that it was just redirecting #130 to here and that the status of #129 is in the upper left-hand corner.
 
 While probably obvious to you as a seasoned developer, it was not immediately obvious to me as someone new to the layout here.

**Comment by TheBusyBiscuit** [comment] 2020-05-01 14:12
@RydelSleak Ah okay, now I get what you mean.
Yeah, no worries, GitHub can be confusing at first.

**Closed** 2020-05-01 14:20 UTC
Labels: Bug Report
